In [1]:
import json
from pathlib import Path

import pandas as pd
import plotly.express as px
from transformers import PreTrainedTokenizer

from pivotal_tokens.constants import get_data_dir, get_artifacts_dir
from pivotal_tokens.hf.loading import  load_tokenizer
from pivotal_tokens.repo import SampleRepo, DictRepo


EXP_DIR = get_data_dir() / 'experiments' / 'exp2.1-sps-tokens' / 'exp2.1.2-qwen3-1.7b-sps-tokens-small-prob-threshold'
# EXP_DIR = get_data_dir() / 'experiments' / 'exp2.1-sps-tokens' / 'exp2.1.3-qwen3-1.7b-sps-tokens-small-prob-threshold'
# EXP_DIR = get_data_dir() / 'experiments' / 'exp2.1-sps-tokens' / 'exp2.1.4-qwen3-1.7b-sps-tokens-small-prob-threshold'
REPO_DIR = EXP_DIR / 'data' / 'repo'
PIVOTAL_TOKENS_FILE = EXP_DIR / 'data' / 'pivotal_tokens.csv'

TRACES_FILE = get_artifacts_dir() / 'exp1_1_qwen3_1_7b_traces.csv'

QWEN3_1_7B_MODEL_ID = 'Qwen/Qwen3-1.7B'

In [2]:
tokenizer = load_tokenizer(QWEN3_1_7B_MODEL_ID)

In [3]:
base_repo = DictRepo(dirpath=REPO_DIR)

In [4]:
traces_df = pd.read_csv(TRACES_FILE)
traces_df[:2]

,id,query,ground_truth,trace
0,5a8b57f25542995d1e6f1371,Were Scott Derrickson and Ed Wood of the same ...,yes,"<think>\nOkay, let's see. The question is whet..."
1,5a8db19d5542994ba4e3dd00,Are Local H and For Against both from the Unit...,yes,"<think>\nOkay, let's see. The question is aski..."

In [5]:
tokens_df = pd.read_csv(PIVOTAL_TOKENS_FILE)
tokens_df['token_ids'] = tokens_df['token_ids'].apply(json.loads)
tokens_df[:2]

,sample_id,span_id,token_ids,span_text,prob_before,prob_after,prob_delta,is_pivotal,pivotal_context,metadata
0,5a8db19d5542994ba4e3dd00,5cac3872-e49d-11f0-93c4-08bfb8a7cb42,[220],,0.58,0.64,0.06,True,<|im_start|>system\nAnswer the following quest...,"{'id': '5a8db19d5542994ba4e3dd00', 'question':..."
1,5a8db19d5542994ba4e3dd00,5caca596-e49d-11f0-93c4-08bfb8a7cb42,[2704],sure,0.62,0.54,-0.08,True,<|im_start|>system\nAnswer the following quest...,"{'id': '5a8db19d5542994ba4e3dd00', 'question':..."

In [6]:
df = pd.merge(traces_df, tokens_df, left_on='id', right_on='sample_id', how='inner')
df[:2]

,id,query,ground_truth,trace,sample_id,span_id,token_ids,span_text,prob_before,prob_after,prob_delta,is_pivotal,pivotal_context,metadata
0,5a8db19d5542994ba4e3dd00,Are Local H and For Against both from the Unit...,yes,"<think>\nOkay, let's see. The question is aski...",5a8db19d5542994ba4e3dd00,5cac3872-e49d-11f0-93c4-08bfb8a7cb42,[220],,0.58,0.64,0.06,True,<|im_start|>system\nAnswer the following quest...,"{'id': '5a8db19d5542994ba4e3dd00', 'question':..."
1,5a8db19d5542994ba4e3dd00,Are Local H and For Against both from the Unit...,yes,"<think>\nOkay, let's see. The question is aski...",5a8db19d5542994ba4e3dd00,5caca596-e49d-11f0-93c4-08bfb8a7cb42,[2704],sure,0.62,0.54,-0.08,True,<|im_start|>system\nAnswer the following quest...,"{'id': '5a8db19d5542994ba4e3dd00', 'question':..."

In [7]:
def get_thinking_trace_from_completion(completion: str) -> str:
    prefix_split_str = '<|im_start|>assistant\n'
    completion_with_suffix = completion.split(prefix_split_str)[-1].strip()

    suffix_split_str = '<|im_end|>'
    completion = completion_with_suffix.split(suffix_split_str)[0].strip()
    return completion


def get_token_length(text: str, tokenizer: PreTrainedTokenizer) -> int:
    token_ids = tokenizer.encode(text, add_special_tokens=False)
    return len(token_ids)

In [8]:
df['partial_trace'] = df['pivotal_context'].apply(get_thinking_trace_from_completion)
df['partial_trace_token_length'] = df['partial_trace'].apply(lambda x: get_token_length(x, tokenizer))
df['trace_token_length'] = df['trace'].apply(lambda x: get_token_length(x, tokenizer))
df['pivotal_token_relative_position'] = (df['partial_trace_token_length'] + 1) / df['trace_token_length']

assert (df['partial_trace_token_length'] < df['trace_token_length']).mean() == 1.0

In [9]:
def get_init_success_prob(sample_id: str, base_repo: DictRepo) -> float | None:
    repo = SampleRepo(base_repo=base_repo, sample_id=sample_id)
    subdivisions = repo.list(path="subdivisions")

    init_prob = None
    for subdiv in subdivisions:
        data = repo.load(path="subdivisions", key=subdiv)
        if len(data['prefix']) == 0 and \
                data['full_seq'].startswith('<think>') and \
                data['full_seq'].endswith('</think>'):
            init_prob = data['prob_before']
            break
    
    return init_prob

In [10]:
df['prob_init'] = df['sample_id'].apply(lambda x: get_init_success_prob(x, base_repo))

In [11]:
df['prob_before_normalized'] = df['prob_before'] / df['prob_init']
df['prob_after_normalized'] = df['prob_after'] / df['prob_init']
df['prob_delta_normalized'] = df['prob_delta'] / df['prob_init']

In [12]:
df['is_positive'] = df['prob_delta'] >= 0

In [13]:
df = df[df['is_pivotal'] == True].copy()

* * *

In [14]:
print(f"Number of pivotal tokens: {len(df)}")

df['is_positive'].value_counts()

Number of pivotal tokens: 3377

is_positive
True     1928
False    1449
Name: count, dtype: int64

In [15]:
df = df[df['is_positive'] == True].copy()

In [16]:
counts = df.groupby('sample_id', as_index=False).agg({'span_id': 'nunique'})
px.histogram(counts, x='span_id', nbins=20, title='Number of Positive Pivotal Tokens per Sample').show()

In [17]:
# Check relation between pivotal token position and trace length
fig = px.scatter(df,
                x='trace_token_length',
                y='partial_trace_token_length',
                hover_data=['sample_id', 'prob_before', 'prob_after', 'prob_init', 'span_text'],
                title='Partial Trace Token Length vs Full Trace Token Length')
fig.show()

In [18]:
# Check if longer traces correlate with lower initial success probability
fig = px.scatter(df,
                 x='trace_token_length' ,
                 y='prob_init',
                 hover_data=['sample_id', 'prob_before', 'prob_after'],
                 title='Initial Success Probability vs Full Trace Token Length'
                 )
fig.show()

In [19]:
# Check relation between pivotal token position and its impact on success probability
fig = px.scatter(df,
                 x='partial_trace_token_length' ,
                 y='prob_delta',
                 hover_data=['sample_id', 'prob_before', 'prob_after', 'prob_init', 'span_text'],
                 title='Pivotal Token Position vs Impact on Success Probability'
                 )
fig.show()


fig = px.scatter(df,
                 x='pivotal_token_relative_position' ,
                 y='prob_delta',
                 hover_data=['sample_id', 'prob_before', 'prob_after', 'prob_init', 'span_text'],
                 title='Pivotal Token Position vs Impact on Success Probability'
                 )
fig.show()

In [20]:
# Check relation between pivotal token position and its normalized impact on success probability
fig = px.scatter(df,
                 x='partial_trace_token_length' ,
                 y='prob_delta_normalized',
                 hover_data=['sample_id', 'prob_before', 'prob_after', 'prob_init', 'span_text'],
                 title='Pivotal Token Position vs Normalized Impact on Success Probability'
                 )
fig.show()


fig = px.scatter(df,
                 x='pivotal_token_relative_position' ,
                 y='prob_delta_normalized',
                 hover_data=['sample_id', 'prob_before', 'prob_after', 'prob_init', 'span_text'],
                 title='Pivotal Token Position vs Normalized Impact on Success Probability'
                 )
fig.show()

In [21]:
df[df['partial_trace_token_length'] == 1]

,id,query,ground_truth,trace,sample_id,span_id,token_ids,span_text,prob_before,prob_after,...,metadata,partial_trace,partial_trace_token_length,trace_token_length,pivotal_token_relative_position,prob_init,prob_before_normalized,prob_after_normalized,prob_delta_normalized,is_positive
167,5ab41d855542996a3a969f4b,Is the Pakistan fast bowler who joined the Ken...,right-hand,"<think>\nOkay, let's see. The question is abou...",5ab41d855542996a3a969f4b,765a3980-e4c6-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.24,0.66,...,"{'id': '5ab41d855542996a3a969f4b', 'question':...",<think>,1,231,0.008658,0.22,1.090909,3.000000,1.909091,True
204,5ab6369655429953192ad2a1,Which Genus has more species Eucryphia or Lepi...,Eucryphia,"<think>\nOkay, let's see. The question is aski...",5ab6369655429953192ad2a1,2193eb2e-e4cd-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.22,0.42,...,"{'id': '5ab6369655429953192ad2a1', 'question':...",<think>,1,301,0.006645,0.20,1.100000,2.100000,1.000000,True
637,5a84d80c5542992a431d1ab5,Which building is used for more different uses...,MiMA,"<think>\nOkay, let's see. The question is aski...",5a84d80c5542992a431d1ab5,41d58886-e511-11f0-93c4-08bfb8a7cb42,[198],\n,0.52,0.62,...,"{'id': '5a84d80c5542992a431d1ab5', 'question':...",<think>,1,452,0.004425,0.56,0.928571,1.107143,0.178571,True
638,5a84d80c5542992a431d1ab5,Which building is used for more different uses...,MiMA,"<think>\nOkay, let's see. The question is aski...",5a84d80c5542992a431d1ab5,41d5d08e-e511-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.62,0.76,...,"{'id': '5a84d80c5542992a431d1ab5', 'question':...",<think>,1,452,0.004425,0.56,1.107143,1.357143,0.250000,True
726,5a7cdcbf55429907fabef04f,"Which film came out first, Still Kicking: Six ...",Still Kicking: Six Artistic Women of Project A...,"<think>\nOkay, let's see. The user is asking w...",5a7cdcbf55429907fabef04f,9a93ed08-e522-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.44,0.52,...,"{'id': '5a7cdcbf55429907fabef04f', 'question':...",<think>,1,307,0.006515,0.42,1.047619,1.238095,0.190476,True
843,5a7af1a955429931da12c98f,Which Karakoram mountain is higher: Distaghil ...,Distaghil Sar,"<think>\nOkay, let's see. The user is asking w...",5a7af1a955429931da12c98f,86158baa-e538-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.44,0.52,...,"{'id': '5a7af1a955429931da12c98f', 'question':...",<think>,1,213,0.009390,0.46,0.956522,1.130435,0.173913,True
943,5ae3790f5542992e3233c415,Are Leopold Lummerstorfer and Valeria Sarmient...,no,"<think>\nOkay, let's see. The question is whet...",5ae3790f5542992e3233c415,ca532582-e544-11f0-93c4-08bfb8a7cb42,[198],\n,0.22,0.28,...,"{'id': '5ae3790f5542992e3233c415', 'question':...",<think>,1,312,0.006410,0.34,0.647059,0.823529,0.176471,True
1264,5a7e14505542995ed0d16685,"Which canal is located farther east, Champlain...",Champlain Canal,"<think>\nOkay, let's see. The question is aski...",5a7e14505542995ed0d16685,3256122e-e587-11f0-93c4-08bfb8a7cb42,[198],\n,0.52,0.70,...,"{'id': '5a7e14505542995ed0d16685', 'question':...",<think>,1,276,0.007246,0.54,0.962963,1.296296,0.333333,True
1360,5a74feb75542996c70cfae6d,"Which man, Ibn Tufail or Ali Qushji, is best k...",Ali Qushji,"<think>\nOkay, let's tackle this question. The...",5a74feb75542996c70cfae6d,d9ac33de-e58f-11f0-93c4-08bfb8a7cb42,[198],\n,0.62,0.98,...,"{'id': '5a74feb75542996c70cfae6d', 'question':...",<think>,1,370,0.005405,0.66,0.939394,1.484848,0.545455,True
1495,5a81f49c5542995ce29dcc9a,The physicist that saw a deficiency in Newton'...,1921,"<think>\nOkay, so the question is about a phys...",5a81f49c5542995ce29dcc9a,80019ebc-e5b4-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.56,0.62,...,"{'id': '5a81f49c5542995ce29dcc9a', 'question':...",<think>,1,543,0.003683,0.52,1.076923,1.192308,0.115385,True
1658,5a7108fa5542994082a3e4ef,"Which battle, the Battle of Cold Harbor, or th...",Second Battle of Bull Run,"<think>\nOkay, let's see. The user is asking w...",5a7108fa5542994082a3e4ef,14aedcbe-e5c4-11f0-93c4-08bfb8a7cb42,[198],\n,0.66,0.74,...,"{'id': '5a7108fa5542994082a3e4ef', 'question':...",<think>,1,109,0.018349,0.58,1.137931,1.275862,0.137931,True
1659,5a7108fa5542994082a3e4ef,"Which battle, the Battle of Cold Harbor, or th...",Second Battle of Bull Run,"<think>\nOkay, let's see. The user is asking w...",5a7108fa5542994082a3e4ef,14af2e26-e5c4-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.74,0.84,...,"{'id': '5a7108fa5542994082a3e4ef', 'question':...",<think>,1,109,0.018349,0.58,1.275862,1.448276,0.172414,True
1849,5ae1e9635542997f29b3c19e,Which airport is located further north in the ...,Grand Junction Regional Airport,"<think>\nOkay, let's see. The question is aski...",5ae1e9635542997f29b3c19e,5f1e6556-e5df-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.26,1.00,...,"{'id': '5ae1e9635542997f29b3c19e', 'question':...",<think>,1,122,0.016393,0.34,0.764706,2.941176,2.176471,True
1873,5abe76c255429965af743f15,What profession does John Landis and Gore Verb...,director,"<think>\nOkay, let's see. The question is aski...",5abe76c255429965af743f15,df3f5d78-e5e2-11f0-93c4-08bfb8a7cb42,[198],\n,0.82,0.92,...,"{'id': '5abe76c255429965af743f15', 'question':...",<think>,1,201,0.009950,0.78,1.051282,1.179487,0.128205,True
2049,5ac3ae885542995ef918c1e7,"Church of All Saints, Doddinghurst is part of ...",Archbishop of Canterbury,"<think>\nOkay, let's see. The question is aski...",5ac3ae885542995ef918c1e7,aef1f3c8-e61f-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.78,0.86,...,"{'id': '5ac3ae885542995ef918c1e7', 'question':...",<think>,1,380,0.005263,0.74,1.054054,1.162162,0.108108,True
2103,5abd38285542993062266c19,Who passed away first Max Ophüls and Shirley C...,Max Ophüls,"<think>\nOkay, let's see. The question is aski...",5abd38285542993062266c19,49fe81b4-e630-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.74,1.00,...,"{'id': '5abd38285542993062266c19', 'question':...",<think>,1,193,0.010363,0.78,0.948718,1.282051,0.333333,True
2219,5a7c66d555429935c91b518f,Who was born first Václav Havel or Penelope Fi...,Penelope Fitzgerald,"<think>\nOkay, let's see. The question is aski...",5a7c66d555429935c91b518f,26236e7e-e63c-11f0-93c4-08bfb8a7cb42,[198],\n,0.34,0.50,...,"{'id': '5a7c66d555429935c91b518f', 'question':...",<think>,1,269,0.007435,0.30,1.133333,1.666667,0.533333,True
2524,5ae022ab554299025d62a428,Which genus is native to arid or semi-desert a...,Echeveria,"<think>\nOkay, let's see. The question is aski...",5ae022ab554299025d62a428,f3e2c03c-e667-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.70,0.98,...,"{'id': '5ae022ab554299025d62a428', 'question':...",<think>,1,247,0.008097,0.78,0.897436,1.256410,0.358974,True
2548,5a74cfed5542993748c896ea,"Which musician or band is from further north, ...",Matthew Good,"<think>\nOkay, let's see. The question is aski...",5a74cfed5542993748c896ea,f8981a06-e66b-11f0-93c4-08bfb8a7cb42,[198],\n,0.20,0.28,...,"{'id': '5a74cfed5542993748c896ea', 'question':...",<think>,1,169,0.011834,0.34,0.588235,0.823529,0.235294,True
2664,5ae0f2bf5542997b2ef7d09e,Which attack resulted with the formal surrend...,The Spring 1945 offensive in Italy,"<think>\nOkay, let's see. The question is aski...",5ae0f2bf5542997b2ef7d09e,6c61d04c-e6a0-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.14,0.88,...,"{'id': '5ae0f2bf5542997b2ef7d09e', 'question':...",<think>,1,1669,0.001198,0.58,0.241379,1.517241,1.275862,True
2826,5a80b35c5542992bc0c4a7b8,Sinimole Paulose's favorite events are the 800...,1896,"<think>\nOkay, let's see. The question is abou...",5a80b35c5542992bc0c4a7b8,1a37812a-e6c5-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.34,0.58,...,"{'id': '5a80b35c5542992bc0c4a7b8', 'question':...",<think>,1,1115,0.001794,0.40,0.850000,1.450000,0.600000,True
2907,5a8ad59355429950cd6afba4,"Which battle, that resulted in the death of Se...",Battle of Chester,"<think>\nOkay, let's try to figure this out. T...",5a8ad59355429950cd6afba4,0368ad88-e6d5-11f0-93c4-08bfb8a7cb42,[198],\n,0.62,0.68,...,"{'id': '5a8ad59355429950cd6afba4', 'question':...",<think>,1,732,0.002732,0.50,1.240000,1.360000,0.120000,True
2935,5a8dde01554299653c1aa159,"In the ""Star Trek"" franchise, DeForest Kelley ...","USS ""Enterprise""","<think>\nOkay, so the question is asking which...",5a8dde01554299653c1aa159,89a5a46c-e6d7-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.44,0.68,...,"{'id': '5a8dde01554299653c1aa159', 'question':...",<think>,1,183,0.010929,0.50,0.880000,1.360000,0.480000,True
2990,5a7744e45542993569682d37,"Who was born first, Juan Rulfo or John le Carré?",Juan Rulfo,"<think>\nOkay, let's see. The question is aski...",5a7744e45542993569682d37,151f7768-e6db-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.46,1.00,...,"{'id': '5a7744e45542993569682d37', 'question':...",<think>,1,125,0.016000,0.56,0.821429,1.785714,0.964286,True
3198,5a73520c5542994cef4bc53f,What is the name the Columbian film loosely ba...,The Little Match Girl,"<think>\nOkay, let's see. The question is abou...",5a73520c5542994cef4bc53f,b1a3d4e4-e735-11f0-93c4-08bfb8a7cb42,[198],\n,0.64,0.78,...,"{'id': '5a73520c5542994cef4bc53f', 'question':...",<think>,1,341,0.005865,0.66,0.969697,1.181818,0.212121,True
3285,5ae54b6355429908b63265cc,Sporobolus and Zea are in the same what?,family,"<think>\nOkay, let's see. The user is asking a...",5ae54b6355429908b63265cc,f1a1e762-e743-11f0-93c4-08bfb8a7cb42,[198],\n,0.46,0.52,...,"{'id': '5ae54b6355429908b63265cc', 'question':...",<think>,1,263,0.007605,0.42,1.095238,1.238095,0.142857,True
3593,5ae4d0ff55429913cc204511,Did Billy Corgan's band The Smashing Pumpkins ...,Greek Fire,"<think>\nOkay, let's see. The question is aski...",5ae4d0ff55429913cc204511,cca71174-e7ae-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.50,0.60,...,"{'id': '5ae4d0ff55429913cc204511', 'question':...",<think>,1,367,0.005450,0.68,0.735294,0.882353,0.147059,True
3658,5a77919d5542995d831811dd,"Who was born first, Marino Girolami or Daniel ...",Marino Girolami,"<think>\nOkay, let's see. The question is aski...",5a77919d5542995d831811dd,0f2113e0-e7b6-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.28,0.92,...,"{'id': '5a77919d5542995d831811dd', 'question':...",<think>,1,168,0.011905,0.56,0.500000,1.642857,1.142857,True
3693,5ac14d0c5542991316484ae2,"Who has worked for more film companies, Kelly ...",Jacques Tourneur,"<think>\nOkay, let's see. The question is aski...",5ac14d0c5542991316484ae2,91b31788-e7c8-11f0-93c4-08bfb8a7cb42,[198],\n,0.62,0.70,...,"{'id': '5ac14d0c5542991316484ae2', 'question':...",<think>,1,682,0.002933,0.78,0.794872,0.897436,0.102564,True
3705,5a8edb7f55429917b4a5bdeb,Is 4 World Trade Center or Trump Palace Condom...,4 World Trade Center,"<think>\nOkay, let's see. The user is asking w...",5a8edb7f55429917b4a5bdeb,0a8e602a-e7cb-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.40,0.54,...,"{'id': '5a8edb7f55429917b4a5bdeb', 'question':...",<think>,1,291,0.006873,0.32,1.250000,1.687500,0.437500,True
3784,5ae1847e55429920d52343ee,"Which has a greater area, Liuzhou or Muling?",Liuzhou,"<think>\nOkay, let's see. The user is asking w...",5ae1847e55429920d52343ee,d8702126-e7d1-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.22,0.94,...,"{'id': '5ae1847e55429920d52343ee', 'question':...",<think>,1,343,0.005831,0.22,1.000000,4.272727,3.272727,True
3822,5a8f1672554299458435d558,"Which genus contains more species, Crowea or D...",Dracula,"<think>\nOkay, let's see. The question is aski...",5a8f1672554299458435d558,29ba99ee-e7d7-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.22,0.62,...,"{'id': '5a8f1672554299458435d558', 'question':...",<think>,1,255,0.007843,0.34,0.647059,1.823529,1.176471,True
3942,5abd077055429965836004f4,Who created and mostly wrote the show that Idr...,David Simon,"<think>\nOkay, let's see. The user is asking a...",5abd077055429965836004f4,00a3a114-e81c-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.66,1.00,...,"{'id': '5abd077055429965836004f4', 'question':...",<think>,1,217,0.009217,0.62,1.064516,1.612903,0.548387,True
3988,5ae0504055429942ec259c6a,"Which genus contains more species, Laurus or S...",Syzygium,"<think>\nOkay, let's tackle this question: ""Wh...",5ae0504055429942ec259c6a,a4ecce06-e81e-11f0-93c4-08bfb8a7cb42,[198],\n,0.78,0.90,...,"{'id': '5ae0504055429942ec259c6a', 'question':...",<think>,1,303,0.006601,0.64,1.218750,1.406250,0.187500,True
3989,5ae0504055429942ec259c6a,"Which genus contains more species, Laurus or S...",Syzygium,"<think>\nOkay, let's tackle this question: ""Wh...",5ae0504055429942ec259c6a,ae8f92a4-e81e-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.90,1.00,...,"{'id': '5ae0504055429942ec259c6a', 'question':...",<think>,1,303,0.006601,0.64,1.406250,1.562500,0.156250,True
3993,5a77bdcb5542997042120b0b,"Who was born first, Morgan Llywelyn or Robert...",Morgan Llywelyn,"<think>\nOkay, so the question is asking who w...",5a77bdcb5542997042120b0b,34471a52-e81f-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.62,0.92,...,"{'id': '5a77bdcb5542997042120b0b', 'question':...",<think>,1,183,0.010929,0.44,1.409091,2.090909,0.681818,True
4044,5a851ba95542997175ce1f81,Rosemary Willis was seen in the grass in what ...,Dallas,"<think>\nOkay, let's see. The question is aski...",5a851ba95542997175ce1f81,489e9a40-e827-11f0-93c4-08bfb8a7cb42,[198],\n,0.60,0.66,...,"{'id': '5a851ba95542997175ce1f81', 'question':...",<think>,1,125,0.016000,0.70,0.857143,0.942857,0.085714,True
4045,5a851ba95542997175ce1f81,Rosemary Willis was seen in the grass in what ...,Dallas,"<think>\nOkay, let's see. The question is aski...",5a851ba95542997175ce1f81,489ef59e-e827-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.66,1.00,...,"{'id': '5a851ba95542997175ce1f81', 'question':...",<think>,1,125,0.016000,0.70,0.942857,1.428571,0.485714,True
4048,5a909a0355429916514e7505,Are Dorothy Parker and Maxine Kumin the same n...,yes,"<think>\nOkay, let's see. The question is whet...",5a909a0355429916514e7505,a099c986-e827-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.84,0.90,...,"{'id': '5a909a0355429916514e7505', 'question':...",<think>,1,157,0.012739,0.72,1.166667,1.250000,0.083333,True
4450,5add8f055542990dbb2f7e6d,Who conducted the negotiations with the owner...,Rudolf Höss,"<think>\nOkay, let's see. The question is aski...",5add8f055542990dbb2f7e6d,551af3a0-e862-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.48,0.82,...,"{'id': '5add8f055542990dbb2f7e6d', 'question':...",<think>,1,317,0.006309,0.58,0.827586,1.413793,0.586207,True
4752,5a7cf3d655429909bec768bf,"Which breed of dog is extinct, the Hawaiian Po...",Hawaiian Poi Dog,"<think>\nOkay, let's see. The question is aski...",5a7cf3d655429909bec768bf,bc099b90-e88d-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.22,0.86,...,"{'id': '5a7cf3d655429909bec768bf', 'question':...",<think>,1,264,0.007576,0.42,0.523810,2.047619,1.523810,True
4858,5ade0cc85542990dbb2f7f37,Is Ordos City more west than Yangzhong?,yes,"<think>\nOkay, let's see. The user is asking i...",5ade0cc85542990dbb2f7f37,7bc7ba12-e89c-11f0-93c4-08bfb8a7cb42,[198],\n,0.48,0.66,...,"{'id': '5ade0cc85542990dbb2f7f37', 'question':...",<think>,1,218,0.009174,0.44,1.090909,1.500000,0.409091,True
4859,5ade0cc85542990dbb2f7f37,Is Ordos City more west than Yangzhong?,yes,"<think>\nOkay, let's see. The user is asking i...",5ade0cc85542990dbb2f7f37,7bc820f6-e89c-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.66,0.98,...,"{'id': '5ade0cc85542990dbb2f7f37', 'question':...",<think>,1,218,0.009174,0.44,1.500000,2.227273,0.727273,True
4897,5abdc0ad55429933744ab81b,"Which band was formed first, Goldfinger or The...",Goldfinger,"<think>\nOkay, let's see. The question is aski...",5abdc0ad55429933744ab81b,276e7316-e8a1-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.48,0.92,...,"{'id': '5abdc0ad55429933744ab81b', 'question':...",<think>,1,148,0.013514,0.60,0.800000,1.533333,0.733333,True
4952,5ae3c1515542992f92d8236a,Which magazine was founded first Science News ...,Science News,"<think>\nOkay, let's see. The question is aski...",5ae3c1515542992f92d8236a,f8874b00-e8a9-11f0-93c4-08bfb8a7cb42,[198],\n,0.84,0.96,...,"{'id': '5ae3c1515542992f92d8236a', 'question':...",<think>,1,188,0.010638,0.80,1.050000,1.200000,0.150000,True
4990,5ab9e477554299232ef4a25d,Which was built first Woolworth Building or 1 ...,Woolworth Building,"<think>\nOkay, let's see. The question is aski...",5ab9e477554299232ef4a25d,6b84d68c-e8b8-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.84,1.00,...,"{'id': '5ab9e477554299232ef4a25d', 'question':...",<think>,1,165,0.012121,0.70,1.200000,1.428571,0.228571,True
4998,5ac1a4ed5542994d76dcce90,Are William James and Bret Easton Ellis both s...,no,"<think>\nOkay, let's see. The question is whet...",5ac1a4ed5542994d76dcce90,eb3a244c-e8bb-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.62,0.74,...,"{'id': '5ac1a4ed5542994d76dcce90', 'question':...",<think>,1,235,0.008511,0.60,1.033333,1.233333,0.200000,True
5017,5a793f505542994bb9456fd1,Who was born first out of Leopold Lummerstorfe...,Leopold Lummerstorfer,"<think>\nOkay, let's see. The question is aski...",5a793f505542994bb9456fd1,a9019aa4-e8bd-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.16,0.98,...,"{'id': '5a793f505542994bb9456fd1', 'question':...",<think>,1,260,0.007692,0.52,0.307692,1.884615,1.576923,True
5038,5ab8494d55429916710eb016,"Which was founded first, University of Califor...","University of California, Santa Barbara","<think>\nOkay, I need to figure out which univ...",5ab8494d55429916710eb016,de7ee32a-e8c3-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.70,0.98,...,"{'id': '5ab8494d55429916710eb016', 'question':...",<think>,1,144,0.013889,0.68,1.029412,1.441176,0.411765,True
5052,5aba3e3355429901930fa78c,Which airport Pago Pago International Airport ...,Chattanooga Metropolitan Airport,"<think>\nOkay, let's see. The user is asking w...",5aba3e3355429901930fa78c,c000a144-e8e2-11f0-93c4-08bfb8a7cb42,[198],\n,0.46,0.54,...,"{'id': '5aba3e3355429901930fa78c', 'question':...",<think>,1,329,0.006079,0.40,1.150000,1.350000,0.200000,True
5208,5a7a34bf5542994f819ef151,In what NCAA division is the team Michael Beas...,Division I,"<think>\nOkay, let's see. The user is asking a...",5a7a34bf5542994f819ef151,767ed102-e8f7-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.56,0.80,...,"{'id': '5a7a34bf5542994f819ef151', 'question':...",<think>,1,302,0.006623,0.78,0.717949,1.025641,0.307692,True
5217,5a77ca3955429967ab1052a3,"Which board game is newer, Splendor or Power G...",Splendor,"<think>\nOkay, I need to figure out which boar...",5a77ca3955429967ab1052a3,dbe91c9c-e8fb-11f0-93c4-08bfb8a7cb42,[198],\n,0.42,0.48,...,"{'id': '5a77ca3955429967ab1052a3', 'question':...",<think>,1,210,0.009524,0.24,1.750000,2.000000,0.250000,True
5234,5aba94e355429901930fa845,Jonathan Groff was 30 years old when he appear...,Lin-Manuel Miranda,"<think>\nOkay, let's see. The question is aski...",5aba94e355429901930fa845,e9dd3d24-e900-11f0-93c4-08bfb8a7cb42,[198],\n,0.40,0.48,...,"{'id': '5aba94e355429901930fa845', 'question':...",<think>,1,859,0.002328,0.44,0.909091,1.090909,0.181818,True
5235,5aba94e355429901930fa845,Jonathan Groff was 30 years old when he appear...,Lin-Manuel Miranda,"<think>\nOkay, let's see. The question is aski...",5aba94e355429901930fa845,e9dd9b16-e900-11f0-93c4-08bfb8a7cb42,[32313],Okay,0.48,0.56,...,"{'id': '5aba94e355429901930fa845', 'question':...",<think>,1,859,0.002328,0.44,1.090909,1.272727,0.181818,True

In [22]:
# TODO:
# 1. Make a list of what I've checked before for the pivotal tokens analysis
# 2. Reproduce all the plots and tables, analyze results, make conclusions. Compare to previous conclusions.
# 3. Prepare random tokens to replace pivotal tokens.
# 4. Prepare script to run the experiments with replaced tokens.
# 5. Run the experiments.